job = {'attempt': 1,
 'config': {'config': {'include_rating_widget': False,
                       'measurement': 'T1',
                       'save_derivatives': False,
                       'save_outputs': False,
                       'verbose_reports': True},
            'destination': {'id': '64a732ef0ffb0ba95c5c679f',
                            'type': 'acquisition'},
            'inputs': {'nifti': {'base': 'file',
                                 'hierarchy': {'id': '64a732ef0ffb0ba95c5c679f',
                                               'type': 'acquisition'},
                                 'location': {'name': 'sub-13_T1w.nii.gz',
                                              'path': '/flywheel/v0/input/nifti/sub-13_T1w.nii.gz'},
                                 'object': {'classification': {'Features': [],
                                                               'Intent': [],
                                                               'Measurement': ['T1']},
                                            'file_id': '64a732fba36314d6133805eb',
                                            'mimetype': 'application/octet-stream',
                                            'modality': 'MR',
                                            'origin': {'id': 'jesusavila@flywheel.io',
                                                       'type': 'user'},
                                            'size': 4888210,
                                            'tags': [],
                                            'type': 'nifti',
                                            'version': 1,
                                            'zip_member_count': None}}}},
 'destination': {'id': '64a732ef0ffb0ba95c5c679f', 'type': 'acquisition'},
 'gear_id': '64a734a17a38c4247c11ce7a',
 'gear_info': {'category': 'qa',
               'id': '64a734a17a38c4247c11ce7a',
               'name': 'mriqc',
               'version': '0.7.0_0.15.1'},
 'id': '64b5bce63a2637356859bf8c',
 'inputs': [{'base': None,
             'found': None,
             'id': '64a732ef0ffb0ba95c5c679f',
             'input': 'nifti',
             'name': 'sub-13_T1w.nii.gz',
             'type': 'acquisition'}],
 'origin': {'id': 'jesusavila@flywheel.io', 'type': 'user'},
 'previous_job_id': None,
 'request': {'inputs': [{'location': '/',
                         'type': 'docker',
                         'uri': 'latest.sse.flywheel.io/mriqc@sha256:6946e8cab89f9b0997812dfa1c200bf8a39363c7ede1ab251744a87868774a2c',
                         'vu': None},
                        {'location': '/flywheel/v0',
                         'type': 'scitran',
                         'uri': '/jobs/64b5bce63a2637356859bf8c/config.json',
                         'vu': None},
                        {'location': '/flywheel/v0/input/nifti',
                         'type': 'scitran',
                         'uri': '/files/64a732fba36314d6133805eb/version/1/download/sub-13_T1w.nii.gz',
                         'vu': None}],
             'outputs': [{'location': '/flywheel/v0/output',
                          'type': 'scitran',
                          'uri': '/engine?level=acquisition&id=64a732ef0ffb0ba95c5c679f&job=64b5bce63a2637356859bf8c',
                          'vu': None}],
             'target': {'command': ['bash', '-c', 'bash -c ./run'],
                        'dir': '/flywheel/v0',
                        'env': {'AFNI_IMSAVE_WARNINGS': 'NO',
                                'AFNI_MODELPATH': '/opt/afni/models',
                                'AFNI_PLUGINPATH': '/opt/afni/plugins',
                                'AFNI_TTATLAS_DATASET': '/opt/afni/atlases',
                                'ANTSPATH': '/usr/lib/ants',
                                'CPATH': '/usr/local/miniconda/include/:',
                                'FLYWHEEL': '/flywheel/v0',
                                'FSLDIR': '/usr/share/fsl/5.0',
                                'FSLMULTIFILEQUIT': 'TRUE',
                                'FSLOUTPUTTYPE': 'NIFTI_GZ',
                                'FSLTCLSH': '/usr/bin/tclsh',
                                'FSLWISH': '/usr/bin/wish',
                                'FW_CONFIG_INCLUDE_RATING_WIDGET': 'false',
                                'FW_CONFIG_MEASUREMENT': 'T1',
                                'FW_CONFIG_SAVE_DERIVATIVES': 'false',
                                'FW_CONFIG_SAVE_OUTPUTS': 'false',
                                'FW_CONFIG_VERBOSE_REPORTS': 'true',
                                'LANG': 'C.UTF-8',
                                'LC_ALL': 'C.UTF-8',
                                'LD_LIBRARY_PATH': '/usr/lib/fsl/5.0:',
                                'MKL_NUM_THREADS': '1',
                                'OMP_NUM_THREADS': '1',
                                'PATH': '/usr/local/miniconda/bin:/opt/afni:/usr/lib/ants:/usr/lib/fsl/5.0:/usr/lib/afni/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
                                'POSSUMDIR': '/usr/share/fsl/5.0',
                                'PWD': '/tmp',
                                'PYTHONNOUSERSITE': '1'},
                        'gid': None,
                        'uid': None}},
 'retried': None,
 'saved_files': None,
 'state': 'running',
 'tags': ['hpc', 'mriqc']}